name: Dump Context

on:
  deployment:
  deployment_status:
  pull_request:

jobs:
  deploy:
    name: Named Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
