name: Mock Deploy

on: deployment_status

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Exit early if it's not successful
      if: github.event.deployment_status.state != 'success'
      run: exit 1
    
    - name: Deploy it!
      run: echo "Deploying!"
